[project]
name = "5580-dm-a4-regression-ts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.0",
    "ruff>=0.15.0",
    "scikit-learn>=1.8.0",
    "statsmodels>=0.14.6",
    "ty>=0.0.15",
]
